# Vault API
@vault_token = hvs.NEEecyuKLrRAb09LeX8dby6J
@vault_address = http://vault.binesty.net
@version = v1
@engine = development

GET {{vault_address}}/{{version}}/{{engine}}/packages-microservices
X-Vault-Token: {{vault_token}}

# Catalog API